name: phantom_re
description: PhantomRE - Android Reverse Engineering Platform (No Root)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_markdown: ^0.7.3
  permission_handler: ^11.3.0
  device_info_plus: ^10.1.0
  archive: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/frida_scripts/
    - assets/xposed_modules/
